---

 - name: TEST
   hosts: PROXY 
   become: true

   roles:
   - role: yum_repo
     repo_file_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
     repo_gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
   - role: firewall
     firewall_ports:
     - { port: 80, proto: tcp, state: enabled }
     - { port: 443, proto: tcp, state: enabled }
   - role: httpd
   - role: docker-ce   

...
