---

 - name: TEST
   hosts: PROXY 
   become: true

   roles:
   - role: firewall
     firewall_ports:
     - { port: 80, proto: tcp, state: enabled }
     - { port: 443, proto: tcp, state: enabled }
   - role: docker-ce   
   - role: docker_network
   - role: nginx

...
