---

 - name: Install Certbot.
   yum: 
     name: certbot
     state: present
     enablerepo: 'epel,rhui-REGION-rhel-server-releases'


 - include_tasks: generate-certificate.yaml
   with_items: "{{ certbot_certs }}"

 - import_tasks: renew-cron.yml

...
