---

 - name: update /etc/hosts file
   become: true
   blockinfile:
     dest: /etc/hosts
     content: "{{lookup('template','hosts-public-aws.j2')}}"
     state: present
     marker: "## {mark} added by ansible ({{ENVIRONMENT_HYPHEN}}{{GROUP_NAME}})"

...
